AWSTemplateFormatVersion: '2010-09-09'

Description: Template to create base roles and security groups for a new account

Parameters:
  EC2DevRoleName:
    Description: Name of the role to be used with dev instnaces
    Type: String
    Default: ec2-devInstance
    MinLength: 5
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9-_]*"
  EC2MLDevRoleName:
    Description: Name of the role to be used with dev instnaces
    Default: ec2-ml-devInstance
    Type: String
    MinLength: 5
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9-_]*"
  NoAccessSG:
    Description: Name of the a SecurityGroup to apply to development instances
    Default: no-access
    Type: String
    MinLength: 5
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9-_]*"
Resources:
  EC2DevRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EC2DevRoleName
      Description: A base role for an EC2 Dev environment that allows EC2 to call services
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  EC2MLDevRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EC2MLDevRoleName
      Description: A base role for an EC2 Dev environment that allows EC2 to call ML services
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
  DevInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Ref EC2DevRoleName
      Roles:
        - !Ref EC2DevRole
  MLDevInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Ref EC2MLDevRoleName
      Roles:
        - !Ref EC2MLDevRole

  NoAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref NoAccessSG
      GroupDescription: No inbound or outbound access

Outputs:
  EC2DevRole:
    Description: Name of the role to be applied to basic dev instances
    Value: !Ref EC2DevRole

  EC2MLDevRole:
    Description: Name of the role to be applied ot ML dev instances
    Value: !Ref EC2MLDevRole

  NoAccessSecurityGroup:
    Description: SecurityGroup with no ingress or egress
    Value: !Ref NoAccessSecurityGroup
