[project]
name = "machine-setup"
version = "0.1.0"
description = "Setups up a dev environment using Ansible"
authors = [{name = "A. Best", email = "bestadam@amazon.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ansible>=10.2.0",
]

[tool.uv]
dev-dependencies = []
