---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: 1.9.6
  - src: geerlingguy.repo-epel
    version: 1.3.0
  - src: geerlingguy.nodejs
    version: 5.0.0
  - src: geerlingguy.pip
    version: 2.0.0
  - name: ansible-role-docker
    src: https://github.com/abest0/ansible-role-docker

collections:
  # Install a collection from Ansible Galaxy.
  - name: amazon.aws
