---
roles:
  # Install a role from Ansible Galaxy.
  - src: geerlingguy.repo-epel
    version: 1.3.0
  - src: geerlingguy.nodejs
  - src: geerlingguy.pip
    version: 2.1.0
  - src: geerlingguy.docker

collections:
  # Install a collection from Ansible Galaxy.
  - name: amazon.aws
