---
roles:
  # Install a role from Ansible Galaxy.
  - src: geerlingguy.repo-epel
    version: 1.3.0
  - src: geerlingguy.nodejs
  - src: geerlingguy.pip
    version: 2.1.0
  - name: ansible-role-docker
    src: https://github.com/abest0/ansible-role-docker

collections:
  # Install a collection from Ansible Galaxy.
  - name: amazon.aws
