---
roles:
  # Install a role from Ansible Galaxy.
  - src: geerlingguy.repo-epel
    version: 1.3.0
  - src: geerlingguy.nodejs
  - src: git+https://github.com/abest0/ansible-role-docker.git

collections:
  # Install a collection from Ansible Galaxy.
  - name: amazon.aws
