---
- name: Uninstall default aws cli
  package:
    name: 'awscli'
    state: 'absent'
  tags:
    - awscli

- name: Download & unzip awscli installation file
  unarchive:
    src: 'https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip'
    dest: /tmp
    remote_src: yes
    creates: /tmp/aws

- name: Installs aws cli
  command: /tmp/aws/install
  become: yes
  args:
    creates: /usr/local/bin/aws
