---
- name: Install vim build dependencies for Ubuntu
  become: yes
  package:
    state: present
    name:
      - git
      - make
      - clang
      - libtool-bin
      - libxt-dev
      - libgtk-3-dev
      - libpython3-dev
      - liblua5.3-dev
  when: ansible_distribution == 'Ubuntu'
  tags: vim

- name: Install vim build dependencies for RedHat
  become: yes
  package:
    state: present
    name:
      - "@Development tools"
      - ctags
      - ncurses-devel
      - git
      - tcl-devel
      - ruby
      - ruby-devel
      - lua
      - lua-devel
      - python3-devel
      - perl
  when: ansible_os_family == 'RedHat'
  tags: vim

- name: Remove existing vim packages
  become: yes
  package:
    state: absent
    name:
      - "{{ 'vim-enhanced' if ansible_os_family == 'RedHat' else 'vim' }}"
      - vim-common
      - "{{ 'vim-filesystem' if ansible_os_family == 'RedHat' else omit }}"
  tags: vim

- name: Create vim build directory
  become_user: "{{ dev_user }}"
  file:
    path: "/home/{{ dev_user }}/oss"
    state: directory
    mode: '0755'
  tags: vim

- name: Clone vim repository
  become_user: "{{ dev_user }}"
  git:
    repo: https://github.com/vim/vim.git
    dest: "{{ vim_dir }}"
    depth: 1
    version: master
  tags: vim

- name: Configure vim build (Ubuntu method)
  become_user: "{{ dev_user }}"
  command:
    argv:
      - ./configure
      - --with-features=huge
      - --enable-multibyte
      - --enable-python3interp=yes
      - --enable-luainterp=yes
      - --enable-cscope
      - --prefix=/usr/local
  args:
    chdir: "{{ vim_dir }}"
  when: ansible_distribution == 'Ubuntu'
  tags: vim

- name: Build vim (Ubuntu method)
  become_user: "{{ dev_user }}"
  make:
    chdir: "{{ vim_dir }}"
    jobs: "{{ ansible_processor_vcpus }}"
  when: ansible_distribution == 'Ubuntu'
  tags: vim

- name: Configure vim build (RedHat method)
  become_user: "{{ dev_user }}"
  command:
    argv:
      - ./configure
      - --with-features=huge
      - --enable-multibyte
      - --enable-rubyinterp=yes
      - --enable-python3interp=yes
      - --enable-perlinterp=yes
      - --enable-luainterp=yes
      - --enable-cscope
      - --prefix=/usr/local
  args:
    chdir: "{{ vim_dir }}"
  when: ansible_os_family == 'RedHat'
  tags: vim

- name: Build vim (RedHat method)
  become_user: "{{ dev_user }}"
  make:
    chdir: "{{ vim_dir }}"
    jobs: "{{ ansible_processor_vcpus }}"
  when: ansible_os_family == 'RedHat'
  tags: vim

- name: Install vim
  become: yes
  command: make install
  args:
    chdir: "{{ vim_dir }}"
  tags: vim
